name: Test Rust
on:
  push:
    paths:
      - 'importer/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'importer/**'
    branches: [ main ]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.70.0
      - run: cd importer && cargo check
    
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.70.0
      - run: cd importer && cargo test
    
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.70.0
          components: rustfmt
      - run: cd importer && cargo fmt --all -- --check
    
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.70.0
          components: clippy
      - run: cd importer && cargo clippy -- -D warnings