name: Test Server
on:
  push:
    paths:
      - 'server/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'server/**'
    branches: [ main ]

jobs:
  composer-symfony-php-tests:
    name: Test Server
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none
          tools: composer:v2
          extensions: pdo pdo_mysql sockets zip gd soap
        env:
          update: true

      - name: Check PHP Version
        run: php -v

      - name: Validate composer.json and composer.lock
        run: cd server && composer validate

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(cd server && composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: cd server && composer install

      #- name: Check Symfony requirements
      #  run: vendor/bin/requirements-checker

      - name: Check the Symfony console
        run: server/bin/console -V

      #- name: PHP-CS-Fixer
      #  uses: docker://oskarstark/php-cs-fixer-ga
      #  with:
      #    args: --config=.php_cs.dist --diff --dry-run

      #- name: Run functionnal and unit tests
      #  run: |
      #    cp .env.ci .env.test
      #    cp .env.ci .env
      #    cp phpunit.ci.xml phpunit.xml
      #    composer test